### ISSUE TITLE
default/searchbnf.conf - second line of comment1 is not being rendered

### ISSUE THREAD

**Issue by barrettnet** [0x616c6578/TA-geoip2#10] opened 2022-06-06 05:30 UTC
I haven't worked out what is causing it but line 10 of the default/searchbnf.conf is not being wrapped into the previous line despite line 9 having a trailing backslash.  I suspect that it may be use of backticks instead of single-quotes around the term ip in line 10.

The issue can be seen by running the following over a period of time that includes a start or restart:
index=_internal sourcetype=splunkd component=IniFile log_level=WARN TERM(geoip2)

You can also see it in the context sensitive help for the command - the second line of the comment is not rendered in the help.

The simple fix would seem to be to manually join line 10 on to the end of line 9.

**Comment by 0x616c6578** [comment] 2022-06-06 08:26
The issue with line 9 was caused by a trailing space (after the backslash).  This was fixed in d6d1f6ef8936f6cb17221df4de775781dceed7e5.

**Closed by 0x616c6578** 2022-06-06 08:26 UTC
